version: 2
registries:
  ghcr:
    type: docker-registry
    url: https://ghcr.io
    username: ${{secrets.CR_USER}}
    password: ${{secrets.CR_PAT}}
    replaces-base: true
updates:
  # For Gradle, update dependencies and plugins to the latest non-major version
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardl"
    labels:
      - "improvement"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
  # For GitHub Actions workflows, update all actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "scalar-labs/scalardl"
    labels:
      - "improvement"
