#!/bin/bash

${SCALAR_SDK_HOME}/client/bin/register-cert -properties ./conf/client.properties
${SCALAR_SDK_HOME}/client/bin/register-contracts -properties ./conf/client.properties -contracts-toml-file ./conf/contracts.toml
