// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface AssetProofRetrievalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.AssetProofRetrievalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string asset_id = 1;</code>
   * @return The assetId.
   */
  java.lang.String getAssetId();
  /**
   * <code>string asset_id = 1;</code>
   * @return The bytes for assetId.
   */
  com.google.protobuf.ByteString
      getAssetIdBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>string entity_id = 3;</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 3;</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>uint32 key_version = 4;</code>
   * @return The keyVersion.
   */
  int getKeyVersion();

  /**
   * <code>bytes signature = 5;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
