// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

/**
 * Protobuf type {@code rpc.AssetProofRetrievalResponse}
 */
public final class AssetProofRetrievalResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.AssetProofRetrievalResponse)
    AssetProofRetrievalResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AssetProofRetrievalResponse.newBuilder() to construct.
  private AssetProofRetrievalResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AssetProofRetrievalResponse() {
    ledgerName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AssetProofRetrievalResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_AssetProofRetrievalResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_AssetProofRetrievalResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalar.dl.rpc.AssetProofRetrievalResponse.class, com.scalar.dl.rpc.AssetProofRetrievalResponse.Builder.class);
  }

  private int bitField0_;
  public static final int PROOF_FIELD_NUMBER = 1;
  private com.scalar.dl.rpc.AssetProof proof_;
  /**
   * <code>.rpc.AssetProof proof = 1;</code>
   * @return Whether the proof field is set.
   */
  @java.lang.Override
  public boolean hasProof() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.rpc.AssetProof proof = 1;</code>
   * @return The proof.
   */
  @java.lang.Override
  public com.scalar.dl.rpc.AssetProof getProof() {
    return proof_ == null ? com.scalar.dl.rpc.AssetProof.getDefaultInstance() : proof_;
  }
  /**
   * <code>.rpc.AssetProof proof = 1;</code>
   */
  @java.lang.Override
  public com.scalar.dl.rpc.AssetProofOrBuilder getProofOrBuilder() {
    return proof_ == null ? com.scalar.dl.rpc.AssetProof.getDefaultInstance() : proof_;
  }

  public static final int LEDGER_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ledgerName_ = "";
  /**
   * <code>string ledger_name = 2;</code>
   * @return The ledgerName.
   */
  @java.lang.Override
  public java.lang.String getLedgerName() {
    java.lang.Object ref = ledgerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ledgerName_ = s;
      return s;
    }
  }
  /**
   * <code>string ledger_name = 2;</code>
   * @return The bytes for ledgerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLedgerNameBytes() {
    java.lang.Object ref = ledgerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ledgerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getProof());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ledgerName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ledgerName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProof());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ledgerName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ledgerName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalar.dl.rpc.AssetProofRetrievalResponse)) {
      return super.equals(obj);
    }
    com.scalar.dl.rpc.AssetProofRetrievalResponse other = (com.scalar.dl.rpc.AssetProofRetrievalResponse) obj;

    if (hasProof() != other.hasProof()) return false;
    if (hasProof()) {
      if (!getProof()
          .equals(other.getProof())) return false;
    }
    if (!getLedgerName()
        .equals(other.getLedgerName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProof()) {
      hash = (37 * hash) + PROOF_FIELD_NUMBER;
      hash = (53 * hash) + getProof().hashCode();
    }
    hash = (37 * hash) + LEDGER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getLedgerName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.dl.rpc.AssetProofRetrievalResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalar.dl.rpc.AssetProofRetrievalResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.AssetProofRetrievalResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.AssetProofRetrievalResponse)
      com.scalar.dl.rpc.AssetProofRetrievalResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_AssetProofRetrievalResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_AssetProofRetrievalResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalar.dl.rpc.AssetProofRetrievalResponse.class, com.scalar.dl.rpc.AssetProofRetrievalResponse.Builder.class);
    }

    // Construct using com.scalar.dl.rpc.AssetProofRetrievalResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProofFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      proof_ = null;
      if (proofBuilder_ != null) {
        proofBuilder_.dispose();
        proofBuilder_ = null;
      }
      ledgerName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_AssetProofRetrievalResponse_descriptor;
    }

    @java.lang.Override
    public com.scalar.dl.rpc.AssetProofRetrievalResponse getDefaultInstanceForType() {
      return com.scalar.dl.rpc.AssetProofRetrievalResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalar.dl.rpc.AssetProofRetrievalResponse build() {
      com.scalar.dl.rpc.AssetProofRetrievalResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalar.dl.rpc.AssetProofRetrievalResponse buildPartial() {
      com.scalar.dl.rpc.AssetProofRetrievalResponse result = new com.scalar.dl.rpc.AssetProofRetrievalResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scalar.dl.rpc.AssetProofRetrievalResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.proof_ = proofBuilder_ == null
            ? proof_
            : proofBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ledgerName_ = ledgerName_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalar.dl.rpc.AssetProofRetrievalResponse) {
        return mergeFrom((com.scalar.dl.rpc.AssetProofRetrievalResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalar.dl.rpc.AssetProofRetrievalResponse other) {
      if (other == com.scalar.dl.rpc.AssetProofRetrievalResponse.getDefaultInstance()) return this;
      if (other.hasProof()) {
        mergeProof(other.getProof());
      }
      if (!other.getLedgerName().isEmpty()) {
        ledgerName_ = other.ledgerName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getProofFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              ledgerName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.scalar.dl.rpc.AssetProof proof_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.dl.rpc.AssetProof, com.scalar.dl.rpc.AssetProof.Builder, com.scalar.dl.rpc.AssetProofOrBuilder> proofBuilder_;
    /**
     * <code>.rpc.AssetProof proof = 1;</code>
     * @return Whether the proof field is set.
     */
    public boolean hasProof() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.rpc.AssetProof proof = 1;</code>
     * @return The proof.
     */
    public com.scalar.dl.rpc.AssetProof getProof() {
      if (proofBuilder_ == null) {
        return proof_ == null ? com.scalar.dl.rpc.AssetProof.getDefaultInstance() : proof_;
      } else {
        return proofBuilder_.getMessage();
      }
    }
    /**
     * <code>.rpc.AssetProof proof = 1;</code>
     */
    public Builder setProof(com.scalar.dl.rpc.AssetProof value) {
      if (proofBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        proof_ = value;
      } else {
        proofBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.rpc.AssetProof proof = 1;</code>
     */
    public Builder setProof(
        com.scalar.dl.rpc.AssetProof.Builder builderForValue) {
      if (proofBuilder_ == null) {
        proof_ = builderForValue.build();
      } else {
        proofBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.rpc.AssetProof proof = 1;</code>
     */
    public Builder mergeProof(com.scalar.dl.rpc.AssetProof value) {
      if (proofBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          proof_ != null &&
          proof_ != com.scalar.dl.rpc.AssetProof.getDefaultInstance()) {
          getProofBuilder().mergeFrom(value);
        } else {
          proof_ = value;
        }
      } else {
        proofBuilder_.mergeFrom(value);
      }
      if (proof_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.rpc.AssetProof proof = 1;</code>
     */
    public Builder clearProof() {
      bitField0_ = (bitField0_ & ~0x00000001);
      proof_ = null;
      if (proofBuilder_ != null) {
        proofBuilder_.dispose();
        proofBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.rpc.AssetProof proof = 1;</code>
     */
    public com.scalar.dl.rpc.AssetProof.Builder getProofBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getProofFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.AssetProof proof = 1;</code>
     */
    public com.scalar.dl.rpc.AssetProofOrBuilder getProofOrBuilder() {
      if (proofBuilder_ != null) {
        return proofBuilder_.getMessageOrBuilder();
      } else {
        return proof_ == null ?
            com.scalar.dl.rpc.AssetProof.getDefaultInstance() : proof_;
      }
    }
    /**
     * <code>.rpc.AssetProof proof = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.dl.rpc.AssetProof, com.scalar.dl.rpc.AssetProof.Builder, com.scalar.dl.rpc.AssetProofOrBuilder> 
        getProofFieldBuilder() {
      if (proofBuilder_ == null) {
        proofBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.dl.rpc.AssetProof, com.scalar.dl.rpc.AssetProof.Builder, com.scalar.dl.rpc.AssetProofOrBuilder>(
                getProof(),
                getParentForChildren(),
                isClean());
        proof_ = null;
      }
      return proofBuilder_;
    }

    private java.lang.Object ledgerName_ = "";
    /**
     * <code>string ledger_name = 2;</code>
     * @return The ledgerName.
     */
    public java.lang.String getLedgerName() {
      java.lang.Object ref = ledgerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ledgerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ledger_name = 2;</code>
     * @return The bytes for ledgerName.
     */
    public com.google.protobuf.ByteString
        getLedgerNameBytes() {
      java.lang.Object ref = ledgerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ledgerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ledger_name = 2;</code>
     * @param value The ledgerName to set.
     * @return This builder for chaining.
     */
    public Builder setLedgerName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ledgerName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string ledger_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLedgerName() {
      ledgerName_ = getDefaultInstance().getLedgerName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string ledger_name = 2;</code>
     * @param value The bytes for ledgerName to set.
     * @return This builder for chaining.
     */
    public Builder setLedgerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ledgerName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.AssetProofRetrievalResponse)
  }

  // @@protoc_insertion_point(class_scope:rpc.AssetProofRetrievalResponse)
  private static final com.scalar.dl.rpc.AssetProofRetrievalResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalar.dl.rpc.AssetProofRetrievalResponse();
  }

  public static com.scalar.dl.rpc.AssetProofRetrievalResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AssetProofRetrievalResponse>
      PARSER = new com.google.protobuf.AbstractParser<AssetProofRetrievalResponse>() {
    @java.lang.Override
    public AssetProofRetrievalResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AssetProofRetrievalResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AssetProofRetrievalResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalar.dl.rpc.AssetProofRetrievalResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

