// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface AssetProofOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.AssetProof)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string asset_id = 1;</code>
   * @return The assetId.
   */
  java.lang.String getAssetId();
  /**
   * <code>string asset_id = 1;</code>
   * @return The bytes for assetId.
   */
  com.google.protobuf.ByteString
      getAssetIdBytes();

  /**
   * <code>uint32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>string nonce = 3;</code>
   * @return The nonce.
   */
  java.lang.String getNonce();
  /**
   * <code>string nonce = 3;</code>
   * @return The bytes for nonce.
   */
  com.google.protobuf.ByteString
      getNonceBytes();

  /**
   * <code>string input = 4;</code>
   * @return The input.
   */
  java.lang.String getInput();
  /**
   * <code>string input = 4;</code>
   * @return The bytes for input.
   */
  com.google.protobuf.ByteString
      getInputBytes();

  /**
   * <code>bytes hash = 5;</code>
   * @return The hash.
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <code>bytes prev_hash = 6;</code>
   * @return The prevHash.
   */
  com.google.protobuf.ByteString getPrevHash();

  /**
   * <code>bytes signature = 7;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
