// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface AssetProofRetrievalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.AssetProofRetrievalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rpc.AssetProof proof = 1;</code>
   * @return Whether the proof field is set.
   */
  boolean hasProof();
  /**
   * <code>.rpc.AssetProof proof = 1;</code>
   * @return The proof.
   */
  com.scalar.dl.rpc.AssetProof getProof();
  /**
   * <code>.rpc.AssetProof proof = 1;</code>
   */
  com.scalar.dl.rpc.AssetProofOrBuilder getProofOrBuilder();

  /**
   * <code>string ledger_name = 2;</code>
   * @return The ledgerName.
   */
  java.lang.String getLedgerName();
  /**
   * <code>string ledger_name = 2;</code>
   * @return The bytes for ledgerName.
   */
  com.google.protobuf.ByteString
      getLedgerNameBytes();
}
