// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface ContractExecutionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ContractExecutionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the result of contract execution
   * </pre>
   *
   * <code>string contract_result = 1;</code>
   * @return The contractResult.
   */
  java.lang.String getContractResult();
  /**
   * <pre>
   * the result of contract execution
   * </pre>
   *
   * <code>string contract_result = 1;</code>
   * @return The bytes for contractResult.
   */
  com.google.protobuf.ByteString
      getContractResultBytes();

  /**
   * <pre>
   * proofs given from the ledger server
   * </pre>
   *
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  java.util.List<com.scalar.dl.rpc.AssetProof> 
      getProofsList();
  /**
   * <pre>
   * proofs given from the ledger server
   * </pre>
   *
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  com.scalar.dl.rpc.AssetProof getProofs(int index);
  /**
   * <pre>
   * proofs given from the ledger server
   * </pre>
   *
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  int getProofsCount();
  /**
   * <pre>
   * proofs given from the ledger server
   * </pre>
   *
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  java.util.List<? extends com.scalar.dl.rpc.AssetProofOrBuilder> 
      getProofsOrBuilderList();
  /**
   * <pre>
   * proofs given from the ledger server
   * </pre>
   *
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  com.scalar.dl.rpc.AssetProofOrBuilder getProofsOrBuilder(
      int index);

  /**
   * <pre>
   * the result of function execution
   * </pre>
   *
   * <code>string function_result = 3;</code>
   * @return The functionResult.
   */
  java.lang.String getFunctionResult();
  /**
   * <pre>
   * the result of function execution
   * </pre>
   *
   * <code>string function_result = 3;</code>
   * @return The bytes for functionResult.
   */
  com.google.protobuf.ByteString
      getFunctionResultBytes();
}
