// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface ContractExecutionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ContractExecutionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string contract_id = 1;</code>
   * @return The contractId.
   */
  java.lang.String getContractId();
  /**
   * <code>string contract_id = 1;</code>
   * @return The bytes for contractId.
   */
  com.google.protobuf.ByteString
      getContractIdBytes();

  /**
   * <code>string contract_argument = 2;</code>
   * @return The contractArgument.
   */
  java.lang.String getContractArgument();
  /**
   * <code>string contract_argument = 2;</code>
   * @return The bytes for contractArgument.
   */
  com.google.protobuf.ByteString
      getContractArgumentBytes();

  /**
   * <code>string entity_id = 3;</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 3;</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>uint32 key_version = 4;</code>
   * @return The keyVersion.
   */
  int getKeyVersion();

  /**
   * <code>string function_argument = 5;</code>
   * @return The functionArgument.
   */
  java.lang.String getFunctionArgument();
  /**
   * <code>string function_argument = 5;</code>
   * @return The bytes for functionArgument.
   */
  com.google.protobuf.ByteString
      getFunctionArgumentBytes();

  /**
   * <code>bytes signature = 6;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <code>bytes auditor_signature = 7;</code>
   * @return The auditorSignature.
   */
  com.google.protobuf.ByteString getAuditorSignature();

  /**
   * <code>bool use_function_ids = 8;</code>
   * @return The useFunctionIds.
   */
  boolean getUseFunctionIds();

  /**
   * <code>repeated string function_ids = 9;</code>
   * @return A list containing the functionIds.
   */
  java.util.List<java.lang.String>
      getFunctionIdsList();
  /**
   * <code>repeated string function_ids = 9;</code>
   * @return The count of functionIds.
   */
  int getFunctionIdsCount();
  /**
   * <code>repeated string function_ids = 9;</code>
   * @param index The index of the element to return.
   * @return The functionIds at the given index.
   */
  java.lang.String getFunctionIds(int index);
  /**
   * <code>repeated string function_ids = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the functionIds at the given index.
   */
  com.google.protobuf.ByteString
      getFunctionIdsBytes(int index);

  /**
   * <code>string nonce = 10;</code>
   * @return The nonce.
   */
  java.lang.String getNonce();
  /**
   * <code>string nonce = 10;</code>
   * @return The bytes for nonce.
   */
  com.google.protobuf.ByteString
      getNonceBytes();
}
