// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

/**
 * Protobuf type {@code rpc.ContractExecutionRequest}
 */
public final class ContractExecutionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.ContractExecutionRequest)
    ContractExecutionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContractExecutionRequest.newBuilder() to construct.
  private ContractExecutionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContractExecutionRequest() {
    contractId_ = "";
    contractArgument_ = "";
    entityId_ = "";
    functionArgument_ = "";
    signature_ = com.google.protobuf.ByteString.EMPTY;
    auditorSignature_ = com.google.protobuf.ByteString.EMPTY;
    functionIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    nonce_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContractExecutionRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ContractExecutionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ContractExecutionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalar.dl.rpc.ContractExecutionRequest.class, com.scalar.dl.rpc.ContractExecutionRequest.Builder.class);
  }

  public static final int CONTRACT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contractId_ = "";
  /**
   * <code>string contract_id = 1;</code>
   * @return The contractId.
   */
  @java.lang.Override
  public java.lang.String getContractId() {
    java.lang.Object ref = contractId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractId_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_id = 1;</code>
   * @return The bytes for contractId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractIdBytes() {
    java.lang.Object ref = contractId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACT_ARGUMENT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contractArgument_ = "";
  /**
   * <code>string contract_argument = 2;</code>
   * @return The contractArgument.
   */
  @java.lang.Override
  public java.lang.String getContractArgument() {
    java.lang.Object ref = contractArgument_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractArgument_ = s;
      return s;
    }
  }
  /**
   * <code>string contract_argument = 2;</code>
   * @return The bytes for contractArgument.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractArgumentBytes() {
    java.lang.Object ref = contractArgument_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractArgument_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTITY_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object entityId_ = "";
  /**
   * <code>string entity_id = 3;</code>
   * @return The entityId.
   */
  @java.lang.Override
  public java.lang.String getEntityId() {
    java.lang.Object ref = entityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entityId_ = s;
      return s;
    }
  }
  /**
   * <code>string entity_id = 3;</code>
   * @return The bytes for entityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntityIdBytes() {
    java.lang.Object ref = entityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_VERSION_FIELD_NUMBER = 4;
  private int keyVersion_ = 0;
  /**
   * <code>uint32 key_version = 4;</code>
   * @return The keyVersion.
   */
  @java.lang.Override
  public int getKeyVersion() {
    return keyVersion_;
  }

  public static final int FUNCTION_ARGUMENT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object functionArgument_ = "";
  /**
   * <code>string function_argument = 5;</code>
   * @return The functionArgument.
   */
  @java.lang.Override
  public java.lang.String getFunctionArgument() {
    java.lang.Object ref = functionArgument_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      functionArgument_ = s;
      return s;
    }
  }
  /**
   * <code>string function_argument = 5;</code>
   * @return The bytes for functionArgument.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFunctionArgumentBytes() {
    java.lang.Object ref = functionArgument_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      functionArgument_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNATURE_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes signature = 6;</code>
   * @return The signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }

  public static final int AUDITOR_SIGNATURE_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString auditorSignature_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes auditor_signature = 7;</code>
   * @return The auditorSignature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAuditorSignature() {
    return auditorSignature_;
  }

  public static final int USE_FUNCTION_IDS_FIELD_NUMBER = 8;
  private boolean useFunctionIds_ = false;
  /**
   * <code>bool use_function_ids = 8;</code>
   * @return The useFunctionIds.
   */
  @java.lang.Override
  public boolean getUseFunctionIds() {
    return useFunctionIds_;
  }

  public static final int FUNCTION_IDS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList functionIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string function_ids = 9;</code>
   * @return A list containing the functionIds.
   */
  public com.google.protobuf.ProtocolStringList
      getFunctionIdsList() {
    return functionIds_;
  }
  /**
   * <code>repeated string function_ids = 9;</code>
   * @return The count of functionIds.
   */
  public int getFunctionIdsCount() {
    return functionIds_.size();
  }
  /**
   * <code>repeated string function_ids = 9;</code>
   * @param index The index of the element to return.
   * @return The functionIds at the given index.
   */
  public java.lang.String getFunctionIds(int index) {
    return functionIds_.get(index);
  }
  /**
   * <code>repeated string function_ids = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the functionIds at the given index.
   */
  public com.google.protobuf.ByteString
      getFunctionIdsBytes(int index) {
    return functionIds_.getByteString(index);
  }

  public static final int NONCE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nonce_ = "";
  /**
   * <code>string nonce = 10;</code>
   * @return The nonce.
   */
  @java.lang.Override
  public java.lang.String getNonce() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nonce_ = s;
      return s;
    }
  }
  /**
   * <code>string nonce = 10;</code>
   * @return The bytes for nonce.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNonceBytes() {
    java.lang.Object ref = nonce_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nonce_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contractId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractArgument_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contractArgument_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entityId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, entityId_);
    }
    if (keyVersion_ != 0) {
      output.writeUInt32(4, keyVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionArgument_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, functionArgument_);
    }
    if (!signature_.isEmpty()) {
      output.writeBytes(6, signature_);
    }
    if (!auditorSignature_.isEmpty()) {
      output.writeBytes(7, auditorSignature_);
    }
    if (useFunctionIds_ != false) {
      output.writeBool(8, useFunctionIds_);
    }
    for (int i = 0; i < functionIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, functionIds_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nonce_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, nonce_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contractId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractArgument_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contractArgument_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entityId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, entityId_);
    }
    if (keyVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, keyVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionArgument_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, functionArgument_);
    }
    if (!signature_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, signature_);
    }
    if (!auditorSignature_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, auditorSignature_);
    }
    if (useFunctionIds_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, useFunctionIds_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < functionIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(functionIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFunctionIdsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nonce_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, nonce_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalar.dl.rpc.ContractExecutionRequest)) {
      return super.equals(obj);
    }
    com.scalar.dl.rpc.ContractExecutionRequest other = (com.scalar.dl.rpc.ContractExecutionRequest) obj;

    if (!getContractId()
        .equals(other.getContractId())) return false;
    if (!getContractArgument()
        .equals(other.getContractArgument())) return false;
    if (!getEntityId()
        .equals(other.getEntityId())) return false;
    if (getKeyVersion()
        != other.getKeyVersion()) return false;
    if (!getFunctionArgument()
        .equals(other.getFunctionArgument())) return false;
    if (!getSignature()
        .equals(other.getSignature())) return false;
    if (!getAuditorSignature()
        .equals(other.getAuditorSignature())) return false;
    if (getUseFunctionIds()
        != other.getUseFunctionIds()) return false;
    if (!getFunctionIdsList()
        .equals(other.getFunctionIdsList())) return false;
    if (!getNonce()
        .equals(other.getNonce())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTRACT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getContractId().hashCode();
    hash = (37 * hash) + CONTRACT_ARGUMENT_FIELD_NUMBER;
    hash = (53 * hash) + getContractArgument().hashCode();
    hash = (37 * hash) + ENTITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEntityId().hashCode();
    hash = (37 * hash) + KEY_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getKeyVersion();
    hash = (37 * hash) + FUNCTION_ARGUMENT_FIELD_NUMBER;
    hash = (53 * hash) + getFunctionArgument().hashCode();
    hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getSignature().hashCode();
    hash = (37 * hash) + AUDITOR_SIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getAuditorSignature().hashCode();
    hash = (37 * hash) + USE_FUNCTION_IDS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUseFunctionIds());
    if (getFunctionIdsCount() > 0) {
      hash = (37 * hash) + FUNCTION_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getFunctionIdsList().hashCode();
    }
    hash = (37 * hash) + NONCE_FIELD_NUMBER;
    hash = (53 * hash) + getNonce().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalar.dl.rpc.ContractExecutionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.ContractExecutionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ContractExecutionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.ContractExecutionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ContractExecutionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.ContractExecutionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ContractExecutionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.dl.rpc.ContractExecutionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalar.dl.rpc.ContractExecutionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalar.dl.rpc.ContractExecutionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ContractExecutionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.dl.rpc.ContractExecutionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalar.dl.rpc.ContractExecutionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.ContractExecutionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.ContractExecutionRequest)
      com.scalar.dl.rpc.ContractExecutionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ContractExecutionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ContractExecutionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalar.dl.rpc.ContractExecutionRequest.class, com.scalar.dl.rpc.ContractExecutionRequest.Builder.class);
    }

    // Construct using com.scalar.dl.rpc.ContractExecutionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contractId_ = "";
      contractArgument_ = "";
      entityId_ = "";
      keyVersion_ = 0;
      functionArgument_ = "";
      signature_ = com.google.protobuf.ByteString.EMPTY;
      auditorSignature_ = com.google.protobuf.ByteString.EMPTY;
      useFunctionIds_ = false;
      functionIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      nonce_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ContractExecutionRequest_descriptor;
    }

    @java.lang.Override
    public com.scalar.dl.rpc.ContractExecutionRequest getDefaultInstanceForType() {
      return com.scalar.dl.rpc.ContractExecutionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalar.dl.rpc.ContractExecutionRequest build() {
      com.scalar.dl.rpc.ContractExecutionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalar.dl.rpc.ContractExecutionRequest buildPartial() {
      com.scalar.dl.rpc.ContractExecutionRequest result = new com.scalar.dl.rpc.ContractExecutionRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scalar.dl.rpc.ContractExecutionRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contractId_ = contractId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.contractArgument_ = contractArgument_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.entityId_ = entityId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.keyVersion_ = keyVersion_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.functionArgument_ = functionArgument_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.signature_ = signature_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.auditorSignature_ = auditorSignature_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.useFunctionIds_ = useFunctionIds_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        functionIds_.makeImmutable();
        result.functionIds_ = functionIds_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.nonce_ = nonce_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalar.dl.rpc.ContractExecutionRequest) {
        return mergeFrom((com.scalar.dl.rpc.ContractExecutionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalar.dl.rpc.ContractExecutionRequest other) {
      if (other == com.scalar.dl.rpc.ContractExecutionRequest.getDefaultInstance()) return this;
      if (!other.getContractId().isEmpty()) {
        contractId_ = other.contractId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getContractArgument().isEmpty()) {
        contractArgument_ = other.contractArgument_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEntityId().isEmpty()) {
        entityId_ = other.entityId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getKeyVersion() != 0) {
        setKeyVersion(other.getKeyVersion());
      }
      if (!other.getFunctionArgument().isEmpty()) {
        functionArgument_ = other.functionArgument_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
        setSignature(other.getSignature());
      }
      if (other.getAuditorSignature() != com.google.protobuf.ByteString.EMPTY) {
        setAuditorSignature(other.getAuditorSignature());
      }
      if (other.getUseFunctionIds() != false) {
        setUseFunctionIds(other.getUseFunctionIds());
      }
      if (!other.functionIds_.isEmpty()) {
        if (functionIds_.isEmpty()) {
          functionIds_ = other.functionIds_;
          bitField0_ |= 0x00000100;
        } else {
          ensureFunctionIdsIsMutable();
          functionIds_.addAll(other.functionIds_);
        }
        onChanged();
      }
      if (!other.getNonce().isEmpty()) {
        nonce_ = other.nonce_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              contractId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              contractArgument_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              entityId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              keyVersion_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              functionArgument_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              signature_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              auditorSignature_ = input.readBytes();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              useFunctionIds_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFunctionIdsIsMutable();
              functionIds_.add(s);
              break;
            } // case 74
            case 82: {
              nonce_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object contractId_ = "";
    /**
     * <code>string contract_id = 1;</code>
     * @return The contractId.
     */
    public java.lang.String getContractId() {
      java.lang.Object ref = contractId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contract_id = 1;</code>
     * @return The bytes for contractId.
     */
    public com.google.protobuf.ByteString
        getContractIdBytes() {
      java.lang.Object ref = contractId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_id = 1;</code>
     * @param value The contractId to set.
     * @return This builder for chaining.
     */
    public Builder setContractId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contractId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractId() {
      contractId_ = getDefaultInstance().getContractId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string contract_id = 1;</code>
     * @param value The bytes for contractId to set.
     * @return This builder for chaining.
     */
    public Builder setContractIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contractId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object contractArgument_ = "";
    /**
     * <code>string contract_argument = 2;</code>
     * @return The contractArgument.
     */
    public java.lang.String getContractArgument() {
      java.lang.Object ref = contractArgument_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractArgument_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contract_argument = 2;</code>
     * @return The bytes for contractArgument.
     */
    public com.google.protobuf.ByteString
        getContractArgumentBytes() {
      java.lang.Object ref = contractArgument_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractArgument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contract_argument = 2;</code>
     * @param value The contractArgument to set.
     * @return This builder for chaining.
     */
    public Builder setContractArgument(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contractArgument_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string contract_argument = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractArgument() {
      contractArgument_ = getDefaultInstance().getContractArgument();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string contract_argument = 2;</code>
     * @param value The bytes for contractArgument to set.
     * @return This builder for chaining.
     */
    public Builder setContractArgumentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contractArgument_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object entityId_ = "";
    /**
     * <code>string entity_id = 3;</code>
     * @return The entityId.
     */
    public java.lang.String getEntityId() {
      java.lang.Object ref = entityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string entity_id = 3;</code>
     * @return The bytes for entityId.
     */
    public com.google.protobuf.ByteString
        getEntityIdBytes() {
      java.lang.Object ref = entityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string entity_id = 3;</code>
     * @param value The entityId to set.
     * @return This builder for chaining.
     */
    public Builder setEntityId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      entityId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string entity_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityId() {
      entityId_ = getDefaultInstance().getEntityId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string entity_id = 3;</code>
     * @param value The bytes for entityId to set.
     * @return This builder for chaining.
     */
    public Builder setEntityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      entityId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int keyVersion_ ;
    /**
     * <code>uint32 key_version = 4;</code>
     * @return The keyVersion.
     */
    @java.lang.Override
    public int getKeyVersion() {
      return keyVersion_;
    }
    /**
     * <code>uint32 key_version = 4;</code>
     * @param value The keyVersion to set.
     * @return This builder for chaining.
     */
    public Builder setKeyVersion(int value) {

      keyVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 key_version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyVersion() {
      bitField0_ = (bitField0_ & ~0x00000008);
      keyVersion_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object functionArgument_ = "";
    /**
     * <code>string function_argument = 5;</code>
     * @return The functionArgument.
     */
    public java.lang.String getFunctionArgument() {
      java.lang.Object ref = functionArgument_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functionArgument_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string function_argument = 5;</code>
     * @return The bytes for functionArgument.
     */
    public com.google.protobuf.ByteString
        getFunctionArgumentBytes() {
      java.lang.Object ref = functionArgument_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functionArgument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string function_argument = 5;</code>
     * @param value The functionArgument to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionArgument(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      functionArgument_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string function_argument = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFunctionArgument() {
      functionArgument_ = getDefaultInstance().getFunctionArgument();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string function_argument = 5;</code>
     * @param value The bytes for functionArgument to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionArgumentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      functionArgument_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes signature = 6;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <code>bytes signature = 6;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      signature_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bytes signature = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000020);
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString auditorSignature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes auditor_signature = 7;</code>
     * @return The auditorSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAuditorSignature() {
      return auditorSignature_;
    }
    /**
     * <code>bytes auditor_signature = 7;</code>
     * @param value The auditorSignature to set.
     * @return This builder for chaining.
     */
    public Builder setAuditorSignature(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      auditorSignature_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bytes auditor_signature = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuditorSignature() {
      bitField0_ = (bitField0_ & ~0x00000040);
      auditorSignature_ = getDefaultInstance().getAuditorSignature();
      onChanged();
      return this;
    }

    private boolean useFunctionIds_ ;
    /**
     * <code>bool use_function_ids = 8;</code>
     * @return The useFunctionIds.
     */
    @java.lang.Override
    public boolean getUseFunctionIds() {
      return useFunctionIds_;
    }
    /**
     * <code>bool use_function_ids = 8;</code>
     * @param value The useFunctionIds to set.
     * @return This builder for chaining.
     */
    public Builder setUseFunctionIds(boolean value) {

      useFunctionIds_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool use_function_ids = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUseFunctionIds() {
      bitField0_ = (bitField0_ & ~0x00000080);
      useFunctionIds_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList functionIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFunctionIdsIsMutable() {
      if (!functionIds_.isModifiable()) {
        functionIds_ = new com.google.protobuf.LazyStringArrayList(functionIds_);
      }
      bitField0_ |= 0x00000100;
    }
    /**
     * <code>repeated string function_ids = 9;</code>
     * @return A list containing the functionIds.
     */
    public com.google.protobuf.ProtocolStringList
        getFunctionIdsList() {
      functionIds_.makeImmutable();
      return functionIds_;
    }
    /**
     * <code>repeated string function_ids = 9;</code>
     * @return The count of functionIds.
     */
    public int getFunctionIdsCount() {
      return functionIds_.size();
    }
    /**
     * <code>repeated string function_ids = 9;</code>
     * @param index The index of the element to return.
     * @return The functionIds at the given index.
     */
    public java.lang.String getFunctionIds(int index) {
      return functionIds_.get(index);
    }
    /**
     * <code>repeated string function_ids = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the functionIds at the given index.
     */
    public com.google.protobuf.ByteString
        getFunctionIdsBytes(int index) {
      return functionIds_.getByteString(index);
    }
    /**
     * <code>repeated string function_ids = 9;</code>
     * @param index The index to set the value at.
     * @param value The functionIds to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFunctionIdsIsMutable();
      functionIds_.set(index, value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string function_ids = 9;</code>
     * @param value The functionIds to add.
     * @return This builder for chaining.
     */
    public Builder addFunctionIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFunctionIdsIsMutable();
      functionIds_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string function_ids = 9;</code>
     * @param values The functionIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllFunctionIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureFunctionIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, functionIds_);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string function_ids = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFunctionIds() {
      functionIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string function_ids = 9;</code>
     * @param value The bytes of the functionIds to add.
     * @return This builder for chaining.
     */
    public Builder addFunctionIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFunctionIdsIsMutable();
      functionIds_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object nonce_ = "";
    /**
     * <code>string nonce = 10;</code>
     * @return The nonce.
     */
    public java.lang.String getNonce() {
      java.lang.Object ref = nonce_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nonce_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nonce = 10;</code>
     * @return The bytes for nonce.
     */
    public com.google.protobuf.ByteString
        getNonceBytes() {
      java.lang.Object ref = nonce_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nonce_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nonce = 10;</code>
     * @param value The nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonce(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nonce_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string nonce = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonce() {
      nonce_ = getDefaultInstance().getNonce();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string nonce = 10;</code>
     * @param value The bytes for nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nonce_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.ContractExecutionRequest)
  }

  // @@protoc_insertion_point(class_scope:rpc.ContractExecutionRequest)
  private static final com.scalar.dl.rpc.ContractExecutionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalar.dl.rpc.ContractExecutionRequest();
  }

  public static com.scalar.dl.rpc.ContractExecutionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContractExecutionRequest>
      PARSER = new com.google.protobuf.AbstractParser<ContractExecutionRequest>() {
    @java.lang.Override
    public ContractExecutionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContractExecutionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContractExecutionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalar.dl.rpc.ContractExecutionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

