// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface ContractsListingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ContractsListingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string entity_id = 1;</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 1;</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>uint32 key_version = 2;</code>
   * @return The keyVersion.
   */
  int getKeyVersion();

  /**
   * <code>string contract_id = 3;</code>
   * @return The contractId.
   */
  java.lang.String getContractId();
  /**
   * <code>string contract_id = 3;</code>
   * @return The bytes for contractId.
   */
  com.google.protobuf.ByteString
      getContractIdBytes();

  /**
   * <code>bytes signature = 4;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
