// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

/**
 * Protobuf type {@code rpc.ContractExecutionResponse}
 */
public final class ContractExecutionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.ContractExecutionResponse)
    ContractExecutionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContractExecutionResponse.newBuilder() to construct.
  private ContractExecutionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContractExecutionResponse() {
    contractResult_ = "";
    proofs_ = java.util.Collections.emptyList();
    functionResult_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContractExecutionResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ContractExecutionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ContractExecutionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalar.dl.rpc.ContractExecutionResponse.class, com.scalar.dl.rpc.ContractExecutionResponse.Builder.class);
  }

  public static final int CONTRACT_RESULT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contractResult_ = "";
  /**
   * <pre>
   * the result of contract execution
   * </pre>
   *
   * <code>string contract_result = 1;</code>
   * @return The contractResult.
   */
  @java.lang.Override
  public java.lang.String getContractResult() {
    java.lang.Object ref = contractResult_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractResult_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the result of contract execution
   * </pre>
   *
   * <code>string contract_result = 1;</code>
   * @return The bytes for contractResult.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractResultBytes() {
    java.lang.Object ref = contractResult_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractResult_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROOFS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.scalar.dl.rpc.AssetProof> proofs_;
  /**
   * <pre>
   * proofs given from the ledger server
   * </pre>
   *
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.scalar.dl.rpc.AssetProof> getProofsList() {
    return proofs_;
  }
  /**
   * <pre>
   * proofs given from the ledger server
   * </pre>
   *
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.scalar.dl.rpc.AssetProofOrBuilder> 
      getProofsOrBuilderList() {
    return proofs_;
  }
  /**
   * <pre>
   * proofs given from the ledger server
   * </pre>
   *
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  @java.lang.Override
  public int getProofsCount() {
    return proofs_.size();
  }
  /**
   * <pre>
   * proofs given from the ledger server
   * </pre>
   *
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  @java.lang.Override
  public com.scalar.dl.rpc.AssetProof getProofs(int index) {
    return proofs_.get(index);
  }
  /**
   * <pre>
   * proofs given from the ledger server
   * </pre>
   *
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  @java.lang.Override
  public com.scalar.dl.rpc.AssetProofOrBuilder getProofsOrBuilder(
      int index) {
    return proofs_.get(index);
  }

  public static final int FUNCTION_RESULT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object functionResult_ = "";
  /**
   * <pre>
   * the result of function execution
   * </pre>
   *
   * <code>string function_result = 3;</code>
   * @return The functionResult.
   */
  @java.lang.Override
  public java.lang.String getFunctionResult() {
    java.lang.Object ref = functionResult_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      functionResult_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the result of function execution
   * </pre>
   *
   * <code>string function_result = 3;</code>
   * @return The bytes for functionResult.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFunctionResultBytes() {
    java.lang.Object ref = functionResult_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      functionResult_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractResult_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contractResult_);
    }
    for (int i = 0; i < proofs_.size(); i++) {
      output.writeMessage(2, proofs_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionResult_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, functionResult_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractResult_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contractResult_);
    }
    for (int i = 0; i < proofs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, proofs_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionResult_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, functionResult_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalar.dl.rpc.ContractExecutionResponse)) {
      return super.equals(obj);
    }
    com.scalar.dl.rpc.ContractExecutionResponse other = (com.scalar.dl.rpc.ContractExecutionResponse) obj;

    if (!getContractResult()
        .equals(other.getContractResult())) return false;
    if (!getProofsList()
        .equals(other.getProofsList())) return false;
    if (!getFunctionResult()
        .equals(other.getFunctionResult())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTRACT_RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getContractResult().hashCode();
    if (getProofsCount() > 0) {
      hash = (37 * hash) + PROOFS_FIELD_NUMBER;
      hash = (53 * hash) + getProofsList().hashCode();
    }
    hash = (37 * hash) + FUNCTION_RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getFunctionResult().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalar.dl.rpc.ContractExecutionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.ContractExecutionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ContractExecutionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.ContractExecutionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ContractExecutionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.ContractExecutionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ContractExecutionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.dl.rpc.ContractExecutionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalar.dl.rpc.ContractExecutionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalar.dl.rpc.ContractExecutionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ContractExecutionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.dl.rpc.ContractExecutionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalar.dl.rpc.ContractExecutionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.ContractExecutionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.ContractExecutionResponse)
      com.scalar.dl.rpc.ContractExecutionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ContractExecutionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ContractExecutionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalar.dl.rpc.ContractExecutionResponse.class, com.scalar.dl.rpc.ContractExecutionResponse.Builder.class);
    }

    // Construct using com.scalar.dl.rpc.ContractExecutionResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contractResult_ = "";
      if (proofsBuilder_ == null) {
        proofs_ = java.util.Collections.emptyList();
      } else {
        proofs_ = null;
        proofsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      functionResult_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ContractExecutionResponse_descriptor;
    }

    @java.lang.Override
    public com.scalar.dl.rpc.ContractExecutionResponse getDefaultInstanceForType() {
      return com.scalar.dl.rpc.ContractExecutionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalar.dl.rpc.ContractExecutionResponse build() {
      com.scalar.dl.rpc.ContractExecutionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalar.dl.rpc.ContractExecutionResponse buildPartial() {
      com.scalar.dl.rpc.ContractExecutionResponse result = new com.scalar.dl.rpc.ContractExecutionResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.scalar.dl.rpc.ContractExecutionResponse result) {
      if (proofsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          proofs_ = java.util.Collections.unmodifiableList(proofs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.proofs_ = proofs_;
      } else {
        result.proofs_ = proofsBuilder_.build();
      }
    }

    private void buildPartial0(com.scalar.dl.rpc.ContractExecutionResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contractResult_ = contractResult_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.functionResult_ = functionResult_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalar.dl.rpc.ContractExecutionResponse) {
        return mergeFrom((com.scalar.dl.rpc.ContractExecutionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalar.dl.rpc.ContractExecutionResponse other) {
      if (other == com.scalar.dl.rpc.ContractExecutionResponse.getDefaultInstance()) return this;
      if (!other.getContractResult().isEmpty()) {
        contractResult_ = other.contractResult_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (proofsBuilder_ == null) {
        if (!other.proofs_.isEmpty()) {
          if (proofs_.isEmpty()) {
            proofs_ = other.proofs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureProofsIsMutable();
            proofs_.addAll(other.proofs_);
          }
          onChanged();
        }
      } else {
        if (!other.proofs_.isEmpty()) {
          if (proofsBuilder_.isEmpty()) {
            proofsBuilder_.dispose();
            proofsBuilder_ = null;
            proofs_ = other.proofs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            proofsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProofsFieldBuilder() : null;
          } else {
            proofsBuilder_.addAllMessages(other.proofs_);
          }
        }
      }
      if (!other.getFunctionResult().isEmpty()) {
        functionResult_ = other.functionResult_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              contractResult_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.scalar.dl.rpc.AssetProof m =
                  input.readMessage(
                      com.scalar.dl.rpc.AssetProof.parser(),
                      extensionRegistry);
              if (proofsBuilder_ == null) {
                ensureProofsIsMutable();
                proofs_.add(m);
              } else {
                proofsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              functionResult_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object contractResult_ = "";
    /**
     * <pre>
     * the result of contract execution
     * </pre>
     *
     * <code>string contract_result = 1;</code>
     * @return The contractResult.
     */
    public java.lang.String getContractResult() {
      java.lang.Object ref = contractResult_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractResult_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the result of contract execution
     * </pre>
     *
     * <code>string contract_result = 1;</code>
     * @return The bytes for contractResult.
     */
    public com.google.protobuf.ByteString
        getContractResultBytes() {
      java.lang.Object ref = contractResult_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the result of contract execution
     * </pre>
     *
     * <code>string contract_result = 1;</code>
     * @param value The contractResult to set.
     * @return This builder for chaining.
     */
    public Builder setContractResult(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contractResult_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the result of contract execution
     * </pre>
     *
     * <code>string contract_result = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractResult() {
      contractResult_ = getDefaultInstance().getContractResult();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the result of contract execution
     * </pre>
     *
     * <code>string contract_result = 1;</code>
     * @param value The bytes for contractResult to set.
     * @return This builder for chaining.
     */
    public Builder setContractResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contractResult_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.scalar.dl.rpc.AssetProof> proofs_ =
      java.util.Collections.emptyList();
    private void ensureProofsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        proofs_ = new java.util.ArrayList<com.scalar.dl.rpc.AssetProof>(proofs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.scalar.dl.rpc.AssetProof, com.scalar.dl.rpc.AssetProof.Builder, com.scalar.dl.rpc.AssetProofOrBuilder> proofsBuilder_;

    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public java.util.List<com.scalar.dl.rpc.AssetProof> getProofsList() {
      if (proofsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(proofs_);
      } else {
        return proofsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public int getProofsCount() {
      if (proofsBuilder_ == null) {
        return proofs_.size();
      } else {
        return proofsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public com.scalar.dl.rpc.AssetProof getProofs(int index) {
      if (proofsBuilder_ == null) {
        return proofs_.get(index);
      } else {
        return proofsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder setProofs(
        int index, com.scalar.dl.rpc.AssetProof value) {
      if (proofsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProofsIsMutable();
        proofs_.set(index, value);
        onChanged();
      } else {
        proofsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder setProofs(
        int index, com.scalar.dl.rpc.AssetProof.Builder builderForValue) {
      if (proofsBuilder_ == null) {
        ensureProofsIsMutable();
        proofs_.set(index, builderForValue.build());
        onChanged();
      } else {
        proofsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder addProofs(com.scalar.dl.rpc.AssetProof value) {
      if (proofsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProofsIsMutable();
        proofs_.add(value);
        onChanged();
      } else {
        proofsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder addProofs(
        int index, com.scalar.dl.rpc.AssetProof value) {
      if (proofsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProofsIsMutable();
        proofs_.add(index, value);
        onChanged();
      } else {
        proofsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder addProofs(
        com.scalar.dl.rpc.AssetProof.Builder builderForValue) {
      if (proofsBuilder_ == null) {
        ensureProofsIsMutable();
        proofs_.add(builderForValue.build());
        onChanged();
      } else {
        proofsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder addProofs(
        int index, com.scalar.dl.rpc.AssetProof.Builder builderForValue) {
      if (proofsBuilder_ == null) {
        ensureProofsIsMutable();
        proofs_.add(index, builderForValue.build());
        onChanged();
      } else {
        proofsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder addAllProofs(
        java.lang.Iterable<? extends com.scalar.dl.rpc.AssetProof> values) {
      if (proofsBuilder_ == null) {
        ensureProofsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, proofs_);
        onChanged();
      } else {
        proofsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder clearProofs() {
      if (proofsBuilder_ == null) {
        proofs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        proofsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder removeProofs(int index) {
      if (proofsBuilder_ == null) {
        ensureProofsIsMutable();
        proofs_.remove(index);
        onChanged();
      } else {
        proofsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public com.scalar.dl.rpc.AssetProof.Builder getProofsBuilder(
        int index) {
      return getProofsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public com.scalar.dl.rpc.AssetProofOrBuilder getProofsOrBuilder(
        int index) {
      if (proofsBuilder_ == null) {
        return proofs_.get(index);  } else {
        return proofsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public java.util.List<? extends com.scalar.dl.rpc.AssetProofOrBuilder> 
         getProofsOrBuilderList() {
      if (proofsBuilder_ != null) {
        return proofsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(proofs_);
      }
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public com.scalar.dl.rpc.AssetProof.Builder addProofsBuilder() {
      return getProofsFieldBuilder().addBuilder(
          com.scalar.dl.rpc.AssetProof.getDefaultInstance());
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public com.scalar.dl.rpc.AssetProof.Builder addProofsBuilder(
        int index) {
      return getProofsFieldBuilder().addBuilder(
          index, com.scalar.dl.rpc.AssetProof.getDefaultInstance());
    }
    /**
     * <pre>
     * proofs given from the ledger server
     * </pre>
     *
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public java.util.List<com.scalar.dl.rpc.AssetProof.Builder> 
         getProofsBuilderList() {
      return getProofsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.scalar.dl.rpc.AssetProof, com.scalar.dl.rpc.AssetProof.Builder, com.scalar.dl.rpc.AssetProofOrBuilder> 
        getProofsFieldBuilder() {
      if (proofsBuilder_ == null) {
        proofsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.scalar.dl.rpc.AssetProof, com.scalar.dl.rpc.AssetProof.Builder, com.scalar.dl.rpc.AssetProofOrBuilder>(
                proofs_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        proofs_ = null;
      }
      return proofsBuilder_;
    }

    private java.lang.Object functionResult_ = "";
    /**
     * <pre>
     * the result of function execution
     * </pre>
     *
     * <code>string function_result = 3;</code>
     * @return The functionResult.
     */
    public java.lang.String getFunctionResult() {
      java.lang.Object ref = functionResult_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functionResult_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the result of function execution
     * </pre>
     *
     * <code>string function_result = 3;</code>
     * @return The bytes for functionResult.
     */
    public com.google.protobuf.ByteString
        getFunctionResultBytes() {
      java.lang.Object ref = functionResult_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functionResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the result of function execution
     * </pre>
     *
     * <code>string function_result = 3;</code>
     * @param value The functionResult to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionResult(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      functionResult_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the result of function execution
     * </pre>
     *
     * <code>string function_result = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFunctionResult() {
      functionResult_ = getDefaultInstance().getFunctionResult();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the result of function execution
     * </pre>
     *
     * <code>string function_result = 3;</code>
     * @param value The bytes for functionResult to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      functionResult_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.ContractExecutionResponse)
  }

  // @@protoc_insertion_point(class_scope:rpc.ContractExecutionResponse)
  private static final com.scalar.dl.rpc.ContractExecutionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalar.dl.rpc.ContractExecutionResponse();
  }

  public static com.scalar.dl.rpc.ContractExecutionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContractExecutionResponse>
      PARSER = new com.google.protobuf.AbstractParser<ContractExecutionResponse>() {
    @java.lang.Override
    public ContractExecutionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ContractExecutionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContractExecutionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalar.dl.rpc.ContractExecutionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

