// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface ExecutionAbortRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ExecutionAbortRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nonce = 1;</code>
   * @return The nonce.
   */
  java.lang.String getNonce();
  /**
   * <code>string nonce = 1;</code>
   * @return The bytes for nonce.
   */
  com.google.protobuf.ByteString
      getNonceBytes();

  /**
   * <code>string entity_id = 2;</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 2;</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>uint32 key_version = 3;</code>
   * @return The keyVersion.
   */
  int getKeyVersion();

  /**
   * <code>bytes signature = 4;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
