// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface ExecutionOrderingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.ExecutionOrderingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes signature = 1;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
