// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

/**
 * Protobuf type {@code rpc.ExecutionValidationRequest}
 */
public final class ExecutionValidationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.ExecutionValidationRequest)
    ExecutionValidationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecutionValidationRequest.newBuilder() to construct.
  private ExecutionValidationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecutionValidationRequest() {
    proofs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecutionValidationRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ExecutionValidationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ExecutionValidationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalar.dl.rpc.ExecutionValidationRequest.class, com.scalar.dl.rpc.ExecutionValidationRequest.Builder.class);
  }

  private int bitField0_;
  public static final int REQUEST_FIELD_NUMBER = 1;
  private com.scalar.dl.rpc.ContractExecutionRequest request_;
  /**
   * <code>.rpc.ContractExecutionRequest request = 1;</code>
   * @return Whether the request field is set.
   */
  @java.lang.Override
  public boolean hasRequest() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.rpc.ContractExecutionRequest request = 1;</code>
   * @return The request.
   */
  @java.lang.Override
  public com.scalar.dl.rpc.ContractExecutionRequest getRequest() {
    return request_ == null ? com.scalar.dl.rpc.ContractExecutionRequest.getDefaultInstance() : request_;
  }
  /**
   * <code>.rpc.ContractExecutionRequest request = 1;</code>
   */
  @java.lang.Override
  public com.scalar.dl.rpc.ContractExecutionRequestOrBuilder getRequestOrBuilder() {
    return request_ == null ? com.scalar.dl.rpc.ContractExecutionRequest.getDefaultInstance() : request_;
  }

  public static final int PROOFS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.scalar.dl.rpc.AssetProof> proofs_;
  /**
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.scalar.dl.rpc.AssetProof> getProofsList() {
    return proofs_;
  }
  /**
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.scalar.dl.rpc.AssetProofOrBuilder> 
      getProofsOrBuilderList() {
    return proofs_;
  }
  /**
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  @java.lang.Override
  public int getProofsCount() {
    return proofs_.size();
  }
  /**
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  @java.lang.Override
  public com.scalar.dl.rpc.AssetProof getProofs(int index) {
    return proofs_.get(index);
  }
  /**
   * <code>repeated .rpc.AssetProof proofs = 2;</code>
   */
  @java.lang.Override
  public com.scalar.dl.rpc.AssetProofOrBuilder getProofsOrBuilder(
      int index) {
    return proofs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRequest());
    }
    for (int i = 0; i < proofs_.size(); i++) {
      output.writeMessage(2, proofs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRequest());
    }
    for (int i = 0; i < proofs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, proofs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalar.dl.rpc.ExecutionValidationRequest)) {
      return super.equals(obj);
    }
    com.scalar.dl.rpc.ExecutionValidationRequest other = (com.scalar.dl.rpc.ExecutionValidationRequest) obj;

    if (hasRequest() != other.hasRequest()) return false;
    if (hasRequest()) {
      if (!getRequest()
          .equals(other.getRequest())) return false;
    }
    if (!getProofsList()
        .equals(other.getProofsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequest()) {
      hash = (37 * hash) + REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getRequest().hashCode();
    }
    if (getProofsCount() > 0) {
      hash = (37 * hash) + PROOFS_FIELD_NUMBER;
      hash = (53 * hash) + getProofsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalar.dl.rpc.ExecutionValidationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.ExecutionValidationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ExecutionValidationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.ExecutionValidationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ExecutionValidationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.ExecutionValidationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ExecutionValidationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.dl.rpc.ExecutionValidationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalar.dl.rpc.ExecutionValidationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalar.dl.rpc.ExecutionValidationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.dl.rpc.ExecutionValidationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.dl.rpc.ExecutionValidationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalar.dl.rpc.ExecutionValidationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.ExecutionValidationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.ExecutionValidationRequest)
      com.scalar.dl.rpc.ExecutionValidationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ExecutionValidationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ExecutionValidationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalar.dl.rpc.ExecutionValidationRequest.class, com.scalar.dl.rpc.ExecutionValidationRequest.Builder.class);
    }

    // Construct using com.scalar.dl.rpc.ExecutionValidationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRequestFieldBuilder();
        getProofsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      request_ = null;
      if (requestBuilder_ != null) {
        requestBuilder_.dispose();
        requestBuilder_ = null;
      }
      if (proofsBuilder_ == null) {
        proofs_ = java.util.Collections.emptyList();
      } else {
        proofs_ = null;
        proofsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_ExecutionValidationRequest_descriptor;
    }

    @java.lang.Override
    public com.scalar.dl.rpc.ExecutionValidationRequest getDefaultInstanceForType() {
      return com.scalar.dl.rpc.ExecutionValidationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalar.dl.rpc.ExecutionValidationRequest build() {
      com.scalar.dl.rpc.ExecutionValidationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalar.dl.rpc.ExecutionValidationRequest buildPartial() {
      com.scalar.dl.rpc.ExecutionValidationRequest result = new com.scalar.dl.rpc.ExecutionValidationRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.scalar.dl.rpc.ExecutionValidationRequest result) {
      if (proofsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          proofs_ = java.util.Collections.unmodifiableList(proofs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.proofs_ = proofs_;
      } else {
        result.proofs_ = proofsBuilder_.build();
      }
    }

    private void buildPartial0(com.scalar.dl.rpc.ExecutionValidationRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.request_ = requestBuilder_ == null
            ? request_
            : requestBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalar.dl.rpc.ExecutionValidationRequest) {
        return mergeFrom((com.scalar.dl.rpc.ExecutionValidationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalar.dl.rpc.ExecutionValidationRequest other) {
      if (other == com.scalar.dl.rpc.ExecutionValidationRequest.getDefaultInstance()) return this;
      if (other.hasRequest()) {
        mergeRequest(other.getRequest());
      }
      if (proofsBuilder_ == null) {
        if (!other.proofs_.isEmpty()) {
          if (proofs_.isEmpty()) {
            proofs_ = other.proofs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureProofsIsMutable();
            proofs_.addAll(other.proofs_);
          }
          onChanged();
        }
      } else {
        if (!other.proofs_.isEmpty()) {
          if (proofsBuilder_.isEmpty()) {
            proofsBuilder_.dispose();
            proofsBuilder_ = null;
            proofs_ = other.proofs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            proofsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProofsFieldBuilder() : null;
          } else {
            proofsBuilder_.addAllMessages(other.proofs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.scalar.dl.rpc.AssetProof m =
                  input.readMessage(
                      com.scalar.dl.rpc.AssetProof.parser(),
                      extensionRegistry);
              if (proofsBuilder_ == null) {
                ensureProofsIsMutable();
                proofs_.add(m);
              } else {
                proofsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.scalar.dl.rpc.ContractExecutionRequest request_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.dl.rpc.ContractExecutionRequest, com.scalar.dl.rpc.ContractExecutionRequest.Builder, com.scalar.dl.rpc.ContractExecutionRequestOrBuilder> requestBuilder_;
    /**
     * <code>.rpc.ContractExecutionRequest request = 1;</code>
     * @return Whether the request field is set.
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.rpc.ContractExecutionRequest request = 1;</code>
     * @return The request.
     */
    public com.scalar.dl.rpc.ContractExecutionRequest getRequest() {
      if (requestBuilder_ == null) {
        return request_ == null ? com.scalar.dl.rpc.ContractExecutionRequest.getDefaultInstance() : request_;
      } else {
        return requestBuilder_.getMessage();
      }
    }
    /**
     * <code>.rpc.ContractExecutionRequest request = 1;</code>
     */
    public Builder setRequest(com.scalar.dl.rpc.ContractExecutionRequest value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
      } else {
        requestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.rpc.ContractExecutionRequest request = 1;</code>
     */
    public Builder setRequest(
        com.scalar.dl.rpc.ContractExecutionRequest.Builder builderForValue) {
      if (requestBuilder_ == null) {
        request_ = builderForValue.build();
      } else {
        requestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.rpc.ContractExecutionRequest request = 1;</code>
     */
    public Builder mergeRequest(com.scalar.dl.rpc.ContractExecutionRequest value) {
      if (requestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          request_ != null &&
          request_ != com.scalar.dl.rpc.ContractExecutionRequest.getDefaultInstance()) {
          getRequestBuilder().mergeFrom(value);
        } else {
          request_ = value;
        }
      } else {
        requestBuilder_.mergeFrom(value);
      }
      if (request_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.rpc.ContractExecutionRequest request = 1;</code>
     */
    public Builder clearRequest() {
      bitField0_ = (bitField0_ & ~0x00000001);
      request_ = null;
      if (requestBuilder_ != null) {
        requestBuilder_.dispose();
        requestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.rpc.ContractExecutionRequest request = 1;</code>
     */
    public com.scalar.dl.rpc.ContractExecutionRequest.Builder getRequestBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.rpc.ContractExecutionRequest request = 1;</code>
     */
    public com.scalar.dl.rpc.ContractExecutionRequestOrBuilder getRequestOrBuilder() {
      if (requestBuilder_ != null) {
        return requestBuilder_.getMessageOrBuilder();
      } else {
        return request_ == null ?
            com.scalar.dl.rpc.ContractExecutionRequest.getDefaultInstance() : request_;
      }
    }
    /**
     * <code>.rpc.ContractExecutionRequest request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalar.dl.rpc.ContractExecutionRequest, com.scalar.dl.rpc.ContractExecutionRequest.Builder, com.scalar.dl.rpc.ContractExecutionRequestOrBuilder> 
        getRequestFieldBuilder() {
      if (requestBuilder_ == null) {
        requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalar.dl.rpc.ContractExecutionRequest, com.scalar.dl.rpc.ContractExecutionRequest.Builder, com.scalar.dl.rpc.ContractExecutionRequestOrBuilder>(
                getRequest(),
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      return requestBuilder_;
    }

    private java.util.List<com.scalar.dl.rpc.AssetProof> proofs_ =
      java.util.Collections.emptyList();
    private void ensureProofsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        proofs_ = new java.util.ArrayList<com.scalar.dl.rpc.AssetProof>(proofs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.scalar.dl.rpc.AssetProof, com.scalar.dl.rpc.AssetProof.Builder, com.scalar.dl.rpc.AssetProofOrBuilder> proofsBuilder_;

    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public java.util.List<com.scalar.dl.rpc.AssetProof> getProofsList() {
      if (proofsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(proofs_);
      } else {
        return proofsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public int getProofsCount() {
      if (proofsBuilder_ == null) {
        return proofs_.size();
      } else {
        return proofsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public com.scalar.dl.rpc.AssetProof getProofs(int index) {
      if (proofsBuilder_ == null) {
        return proofs_.get(index);
      } else {
        return proofsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder setProofs(
        int index, com.scalar.dl.rpc.AssetProof value) {
      if (proofsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProofsIsMutable();
        proofs_.set(index, value);
        onChanged();
      } else {
        proofsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder setProofs(
        int index, com.scalar.dl.rpc.AssetProof.Builder builderForValue) {
      if (proofsBuilder_ == null) {
        ensureProofsIsMutable();
        proofs_.set(index, builderForValue.build());
        onChanged();
      } else {
        proofsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder addProofs(com.scalar.dl.rpc.AssetProof value) {
      if (proofsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProofsIsMutable();
        proofs_.add(value);
        onChanged();
      } else {
        proofsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder addProofs(
        int index, com.scalar.dl.rpc.AssetProof value) {
      if (proofsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProofsIsMutable();
        proofs_.add(index, value);
        onChanged();
      } else {
        proofsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder addProofs(
        com.scalar.dl.rpc.AssetProof.Builder builderForValue) {
      if (proofsBuilder_ == null) {
        ensureProofsIsMutable();
        proofs_.add(builderForValue.build());
        onChanged();
      } else {
        proofsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder addProofs(
        int index, com.scalar.dl.rpc.AssetProof.Builder builderForValue) {
      if (proofsBuilder_ == null) {
        ensureProofsIsMutable();
        proofs_.add(index, builderForValue.build());
        onChanged();
      } else {
        proofsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder addAllProofs(
        java.lang.Iterable<? extends com.scalar.dl.rpc.AssetProof> values) {
      if (proofsBuilder_ == null) {
        ensureProofsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, proofs_);
        onChanged();
      } else {
        proofsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder clearProofs() {
      if (proofsBuilder_ == null) {
        proofs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        proofsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public Builder removeProofs(int index) {
      if (proofsBuilder_ == null) {
        ensureProofsIsMutable();
        proofs_.remove(index);
        onChanged();
      } else {
        proofsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public com.scalar.dl.rpc.AssetProof.Builder getProofsBuilder(
        int index) {
      return getProofsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public com.scalar.dl.rpc.AssetProofOrBuilder getProofsOrBuilder(
        int index) {
      if (proofsBuilder_ == null) {
        return proofs_.get(index);  } else {
        return proofsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public java.util.List<? extends com.scalar.dl.rpc.AssetProofOrBuilder> 
         getProofsOrBuilderList() {
      if (proofsBuilder_ != null) {
        return proofsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(proofs_);
      }
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public com.scalar.dl.rpc.AssetProof.Builder addProofsBuilder() {
      return getProofsFieldBuilder().addBuilder(
          com.scalar.dl.rpc.AssetProof.getDefaultInstance());
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public com.scalar.dl.rpc.AssetProof.Builder addProofsBuilder(
        int index) {
      return getProofsFieldBuilder().addBuilder(
          index, com.scalar.dl.rpc.AssetProof.getDefaultInstance());
    }
    /**
     * <code>repeated .rpc.AssetProof proofs = 2;</code>
     */
    public java.util.List<com.scalar.dl.rpc.AssetProof.Builder> 
         getProofsBuilderList() {
      return getProofsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.scalar.dl.rpc.AssetProof, com.scalar.dl.rpc.AssetProof.Builder, com.scalar.dl.rpc.AssetProofOrBuilder> 
        getProofsFieldBuilder() {
      if (proofsBuilder_ == null) {
        proofsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.scalar.dl.rpc.AssetProof, com.scalar.dl.rpc.AssetProof.Builder, com.scalar.dl.rpc.AssetProofOrBuilder>(
                proofs_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        proofs_ = null;
      }
      return proofsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.ExecutionValidationRequest)
  }

  // @@protoc_insertion_point(class_scope:rpc.ExecutionValidationRequest)
  private static final com.scalar.dl.rpc.ExecutionValidationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalar.dl.rpc.ExecutionValidationRequest();
  }

  public static com.scalar.dl.rpc.ExecutionValidationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecutionValidationRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExecutionValidationRequest>() {
    @java.lang.Override
    public ExecutionValidationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecutionValidationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecutionValidationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalar.dl.rpc.ExecutionValidationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

