// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

/**
 * Protobuf type {@code rpc.FunctionRegistrationRequest}
 */
public final class FunctionRegistrationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpc.FunctionRegistrationRequest)
    FunctionRegistrationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FunctionRegistrationRequest.newBuilder() to construct.
  private FunctionRegistrationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FunctionRegistrationRequest() {
    functionId_ = "";
    functionBinaryName_ = "";
    functionByteCode_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FunctionRegistrationRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_FunctionRegistrationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_FunctionRegistrationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalar.dl.rpc.FunctionRegistrationRequest.class, com.scalar.dl.rpc.FunctionRegistrationRequest.Builder.class);
  }

  public static final int FUNCTION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object functionId_ = "";
  /**
   * <code>string function_id = 1;</code>
   * @return The functionId.
   */
  @java.lang.Override
  public java.lang.String getFunctionId() {
    java.lang.Object ref = functionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      functionId_ = s;
      return s;
    }
  }
  /**
   * <code>string function_id = 1;</code>
   * @return The bytes for functionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFunctionIdBytes() {
    java.lang.Object ref = functionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      functionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FUNCTION_BINARY_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object functionBinaryName_ = "";
  /**
   * <code>string function_binary_name = 2;</code>
   * @return The functionBinaryName.
   */
  @java.lang.Override
  public java.lang.String getFunctionBinaryName() {
    java.lang.Object ref = functionBinaryName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      functionBinaryName_ = s;
      return s;
    }
  }
  /**
   * <code>string function_binary_name = 2;</code>
   * @return The bytes for functionBinaryName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFunctionBinaryNameBytes() {
    java.lang.Object ref = functionBinaryName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      functionBinaryName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FUNCTION_BYTE_CODE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString functionByteCode_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes function_byte_code = 3;</code>
   * @return The functionByteCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getFunctionByteCode() {
    return functionByteCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, functionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionBinaryName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, functionBinaryName_);
    }
    if (!functionByteCode_.isEmpty()) {
      output.writeBytes(3, functionByteCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, functionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionBinaryName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, functionBinaryName_);
    }
    if (!functionByteCode_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, functionByteCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalar.dl.rpc.FunctionRegistrationRequest)) {
      return super.equals(obj);
    }
    com.scalar.dl.rpc.FunctionRegistrationRequest other = (com.scalar.dl.rpc.FunctionRegistrationRequest) obj;

    if (!getFunctionId()
        .equals(other.getFunctionId())) return false;
    if (!getFunctionBinaryName()
        .equals(other.getFunctionBinaryName())) return false;
    if (!getFunctionByteCode()
        .equals(other.getFunctionByteCode())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FUNCTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFunctionId().hashCode();
    hash = (37 * hash) + FUNCTION_BINARY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFunctionBinaryName().hashCode();
    hash = (37 * hash) + FUNCTION_BYTE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getFunctionByteCode().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalar.dl.rpc.FunctionRegistrationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalar.dl.rpc.FunctionRegistrationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpc.FunctionRegistrationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpc.FunctionRegistrationRequest)
      com.scalar.dl.rpc.FunctionRegistrationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_FunctionRegistrationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_FunctionRegistrationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalar.dl.rpc.FunctionRegistrationRequest.class, com.scalar.dl.rpc.FunctionRegistrationRequest.Builder.class);
    }

    // Construct using com.scalar.dl.rpc.FunctionRegistrationRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      functionId_ = "";
      functionBinaryName_ = "";
      functionByteCode_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalar.dl.rpc.ScalarProto.internal_static_rpc_FunctionRegistrationRequest_descriptor;
    }

    @java.lang.Override
    public com.scalar.dl.rpc.FunctionRegistrationRequest getDefaultInstanceForType() {
      return com.scalar.dl.rpc.FunctionRegistrationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalar.dl.rpc.FunctionRegistrationRequest build() {
      com.scalar.dl.rpc.FunctionRegistrationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalar.dl.rpc.FunctionRegistrationRequest buildPartial() {
      com.scalar.dl.rpc.FunctionRegistrationRequest result = new com.scalar.dl.rpc.FunctionRegistrationRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scalar.dl.rpc.FunctionRegistrationRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.functionId_ = functionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.functionBinaryName_ = functionBinaryName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.functionByteCode_ = functionByteCode_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalar.dl.rpc.FunctionRegistrationRequest) {
        return mergeFrom((com.scalar.dl.rpc.FunctionRegistrationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalar.dl.rpc.FunctionRegistrationRequest other) {
      if (other == com.scalar.dl.rpc.FunctionRegistrationRequest.getDefaultInstance()) return this;
      if (!other.getFunctionId().isEmpty()) {
        functionId_ = other.functionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFunctionBinaryName().isEmpty()) {
        functionBinaryName_ = other.functionBinaryName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getFunctionByteCode() != com.google.protobuf.ByteString.EMPTY) {
        setFunctionByteCode(other.getFunctionByteCode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              functionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              functionBinaryName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              functionByteCode_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object functionId_ = "";
    /**
     * <code>string function_id = 1;</code>
     * @return The functionId.
     */
    public java.lang.String getFunctionId() {
      java.lang.Object ref = functionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string function_id = 1;</code>
     * @return The bytes for functionId.
     */
    public com.google.protobuf.ByteString
        getFunctionIdBytes() {
      java.lang.Object ref = functionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string function_id = 1;</code>
     * @param value The functionId to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      functionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string function_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFunctionId() {
      functionId_ = getDefaultInstance().getFunctionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string function_id = 1;</code>
     * @param value The bytes for functionId to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      functionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object functionBinaryName_ = "";
    /**
     * <code>string function_binary_name = 2;</code>
     * @return The functionBinaryName.
     */
    public java.lang.String getFunctionBinaryName() {
      java.lang.Object ref = functionBinaryName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functionBinaryName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string function_binary_name = 2;</code>
     * @return The bytes for functionBinaryName.
     */
    public com.google.protobuf.ByteString
        getFunctionBinaryNameBytes() {
      java.lang.Object ref = functionBinaryName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functionBinaryName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string function_binary_name = 2;</code>
     * @param value The functionBinaryName to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionBinaryName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      functionBinaryName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string function_binary_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFunctionBinaryName() {
      functionBinaryName_ = getDefaultInstance().getFunctionBinaryName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string function_binary_name = 2;</code>
     * @param value The bytes for functionBinaryName to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionBinaryNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      functionBinaryName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString functionByteCode_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes function_byte_code = 3;</code>
     * @return The functionByteCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFunctionByteCode() {
      return functionByteCode_;
    }
    /**
     * <code>bytes function_byte_code = 3;</code>
     * @param value The functionByteCode to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionByteCode(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      functionByteCode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bytes function_byte_code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFunctionByteCode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      functionByteCode_ = getDefaultInstance().getFunctionByteCode();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rpc.FunctionRegistrationRequest)
  }

  // @@protoc_insertion_point(class_scope:rpc.FunctionRegistrationRequest)
  private static final com.scalar.dl.rpc.FunctionRegistrationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalar.dl.rpc.FunctionRegistrationRequest();
  }

  public static com.scalar.dl.rpc.FunctionRegistrationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FunctionRegistrationRequest>
      PARSER = new com.google.protobuf.AbstractParser<FunctionRegistrationRequest>() {
    @java.lang.Override
    public FunctionRegistrationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FunctionRegistrationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FunctionRegistrationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalar.dl.rpc.FunctionRegistrationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

