// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface FunctionRegistrationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.FunctionRegistrationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string function_id = 1;</code>
   * @return The functionId.
   */
  java.lang.String getFunctionId();
  /**
   * <code>string function_id = 1;</code>
   * @return The bytes for functionId.
   */
  com.google.protobuf.ByteString
      getFunctionIdBytes();

  /**
   * <code>string function_binary_name = 2;</code>
   * @return The functionBinaryName.
   */
  java.lang.String getFunctionBinaryName();
  /**
   * <code>string function_binary_name = 2;</code>
   * @return The bytes for functionBinaryName.
   */
  com.google.protobuf.ByteString
      getFunctionBinaryNameBytes();

  /**
   * <code>bytes function_byte_code = 3;</code>
   * @return The functionByteCode.
   */
  com.google.protobuf.ByteString getFunctionByteCode();
}
