// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public final class ScalarProto {
  private ScalarProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_CertificateRegistrationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_CertificateRegistrationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_SecretRegistrationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_SecretRegistrationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_FunctionRegistrationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_FunctionRegistrationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ContractRegistrationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ContractRegistrationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ContractsListingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ContractsListingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ContractExecutionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ContractExecutionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_LedgerValidationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_LedgerValidationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_AssetProofRetrievalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_AssetProofRetrievalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ExecutionAbortRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ExecutionAbortRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_StateRetrievalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_StateRetrievalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ExecutionValidationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ExecutionValidationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ContractsListingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ContractsListingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ContractExecutionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ContractExecutionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_LedgerValidationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_LedgerValidationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_AssetProofRetrievalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_AssetProofRetrievalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_AssetProof_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_AssetProof_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ExecutionAbortResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ExecutionAbortResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_StateRetrievalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_StateRetrievalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_ExecutionOrderingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_ExecutionOrderingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014scalar.proto\022\003rpc\032\033google/protobuf/emp" +
      "ty.proto\032\033scalar/protobuf/admin.proto\"Z\n" +
      "\036CertificateRegistrationRequest\022\021\n\tentit" +
      "y_id\030\001 \001(\t\022\023\n\013key_version\030\002 \001(\r\022\020\n\010cert_" +
      "pem\030\003 \001(\t\"W\n\031SecretRegistrationRequest\022\021" +
      "\n\tentity_id\030\001 \001(\t\022\023\n\013key_version\030\002 \001(\r\022\022" +
      "\n\nsecret_key\030\003 \001(\t\"l\n\033FunctionRegistrati" +
      "onRequest\022\023\n\013function_id\030\001 \001(\t\022\034\n\024functi" +
      "on_binary_name\030\002 \001(\t\022\032\n\022function_byte_co" +
      "de\030\003 \001(\014\"\304\001\n\033ContractRegistrationRequest" +
      "\022\023\n\013contract_id\030\001 \001(\t\022\034\n\024contract_binary" +
      "_name\030\002 \001(\t\022\032\n\022contract_byte_code\030\003 \001(\014\022" +
      "\033\n\023contract_properties\030\004 \001(\t\022\021\n\tentity_i" +
      "d\030\005 \001(\t\022\023\n\013key_version\030\006 \001(\r\022\021\n\tsignatur" +
      "e\030\007 \001(\014\"i\n\027ContractsListingRequest\022\021\n\ten" +
      "tity_id\030\001 \001(\t\022\023\n\013key_version\030\002 \001(\r\022\023\n\013co" +
      "ntract_id\030\003 \001(\t\022\021\n\tsignature\030\004 \001(\014\"\372\001\n\030C" +
      "ontractExecutionRequest\022\023\n\013contract_id\030\001" +
      " \001(\t\022\031\n\021contract_argument\030\002 \001(\t\022\021\n\tentit" +
      "y_id\030\003 \001(\t\022\023\n\013key_version\030\004 \001(\r\022\031\n\021funct" +
      "ion_argument\030\005 \001(\t\022\021\n\tsignature\030\006 \001(\014\022\031\n" +
      "\021auditor_signature\030\007 \001(\014\022\030\n\020use_function" +
      "_ids\030\010 \001(\010\022\024\n\014function_ids\030\t \003(\t\022\r\n\005nonc" +
      "e\030\n \001(\t\"\212\001\n\027LedgerValidationRequest\022\020\n\010a" +
      "sset_id\030\001 \001(\t\022\021\n\tstart_age\030\002 \001(\r\022\017\n\007end_" +
      "age\030\003 \001(\r\022\021\n\tentity_id\030\004 \001(\t\022\023\n\013key_vers" +
      "ion\030\005 \001(\r\022\021\n\tsignature\030\006 \001(\014\"v\n\032AssetPro" +
      "ofRetrievalRequest\022\020\n\010asset_id\030\001 \001(\t\022\013\n\003" +
      "age\030\002 \001(\005\022\021\n\tentity_id\030\003 \001(\t\022\023\n\013key_vers" +
      "ion\030\004 \001(\r\022\021\n\tsignature\030\005 \001(\014\"a\n\025Executio" +
      "nAbortRequest\022\r\n\005nonce\030\001 \001(\t\022\021\n\tentity_i" +
      "d\030\002 \001(\t\022\023\n\013key_version\030\003 \001(\r\022\021\n\tsignatur" +
      "e\030\004 \001(\014\"/\n\025StateRetrievalRequest\022\026\n\016tran" +
      "saction_id\030\001 \001(\t\"m\n\032ExecutionValidationR" +
      "equest\022.\n\007request\030\001 \001(\0132\035.rpc.ContractEx" +
      "ecutionRequest\022\037\n\006proofs\030\002 \003(\0132\017.rpc.Ass" +
      "etProof\"(\n\030ContractsListingResponse\022\014\n\004j" +
      "son\030\001 \001(\t\"n\n\031ContractExecutionResponse\022\027" +
      "\n\017contract_result\030\001 \001(\t\022\037\n\006proofs\030\002 \003(\0132" +
      "\017.rpc.AssetProof\022\027\n\017function_result\030\003 \001(" +
      "\t\"O\n\030LedgerValidationResponse\022\023\n\013status_" +
      "code\030\001 \001(\r\022\036\n\005proof\030\002 \001(\0132\017.rpc.AssetPro" +
      "of\"R\n\033AssetProofRetrievalResponse\022\036\n\005pro" +
      "of\030\001 \001(\0132\017.rpc.AssetProof\022\023\n\013ledger_name" +
      "\030\002 \001(\t\"}\n\nAssetProof\022\020\n\010asset_id\030\001 \001(\t\022\013" +
      "\n\003age\030\002 \001(\r\022\r\n\005nonce\030\003 \001(\t\022\r\n\005input\030\004 \001(" +
      "\t\022\014\n\004hash\030\005 \001(\014\022\021\n\tprev_hash\030\006 \001(\014\022\021\n\tsi" +
      "gnature\030\007 \001(\014\">\n\026ExecutionAbortResponse\022" +
      "$\n\005state\030\001 \001(\0162\025.rpc.TransactionState\">\n" +
      "\026StateRetrievalResponse\022$\n\005state\030\001 \001(\0162\025" +
      ".rpc.TransactionState\"\'\n\006Status\022\014\n\004code\030" +
      "\001 \001(\r\022\017\n\007message\030\002 \001(\t\".\n\031ExecutionOrder" +
      "ingResponse\022\021\n\tsignature\030\001 \001(\014*\224\001\n\020Trans" +
      "actionState\022!\n\035TRANSACTION_STATE_UNSPECI" +
      "FIED\020\000\022\037\n\033TRANSACTION_STATE_COMMITTED\020\001\022" +
      "\035\n\031TRANSACTION_STATE_ABORTED\020\002\022\035\n\031TRANSA" +
      "CTION_STATE_UNKNOWN\020\0032\365\003\n\006Ledger\022N\n\020Regi" +
      "sterContract\022 .rpc.ContractRegistrationR" +
      "equest\032\026.google.protobuf.Empty\"\000\022N\n\rList" +
      "Contracts\022\034.rpc.ContractsListingRequest\032" +
      "\035.rpc.ContractsListingResponse\"\000\022R\n\017Exec" +
      "uteContract\022\035.rpc.ContractExecutionReque" +
      "st\032\036.rpc.ContractExecutionResponse\"\000\022O\n\016" +
      "ValidateLedger\022\034.rpc.LedgerValidationReq" +
      "uest\032\035.rpc.LedgerValidationResponse\"\000\022Y\n" +
      "\022RetrieveAssetProof\022\037.rpc.AssetProofRetr" +
      "ievalRequest\032 .rpc.AssetProofRetrievalRe" +
      "sponse\"\000\022K\n\016AbortExecution\022\032.rpc.Executi" +
      "onAbortRequest\032\033.rpc.ExecutionAbortRespo" +
      "nse\"\0002\311\002\n\020LedgerPrivileged\022M\n\014RegisterCe" +
      "rt\022#.rpc.CertificateRegistrationRequest\032" +
      "\026.google.protobuf.Empty\"\000\022J\n\016RegisterSec" +
      "ret\022\036.rpc.SecretRegistrationRequest\032\026.go" +
      "ogle.protobuf.Empty\"\000\022N\n\020RegisterFunctio" +
      "n\022 .rpc.FunctionRegistrationRequest\032\026.go" +
      "ogle.protobuf.Empty\"\000\022J\n\rRetrieveState\022\032" +
      ".rpc.StateRetrievalRequest\032\033.rpc.StateRe" +
      "trievalResponse\"\0002\324\002\n\007Auditor\022N\n\020Registe" +
      "rContract\022 .rpc.ContractRegistrationRequ" +
      "est\032\026.google.protobuf.Empty\"\000\022N\n\rListCon" +
      "tracts\022\034.rpc.ContractsListingRequest\032\035.r" +
      "pc.ContractsListingResponse\"\000\022Q\n\016OrderEx" +
      "ecution\022\035.rpc.ContractExecutionRequest\032\036" +
      ".rpc.ExecutionOrderingResponse\"\000\022V\n\021Vali" +
      "dateExecution\022\037.rpc.ExecutionValidationR" +
      "equest\032\036.rpc.ContractExecutionResponse\"\000" +
      "2\256\001\n\021AuditorPrivileged\022M\n\014RegisterCert\022#" +
      ".rpc.CertificateRegistrationRequest\032\026.go" +
      "ogle.protobuf.Empty\"\000\022J\n\016RegisterSecret\022" +
      "\036.rpc.SecretRegistrationRequest\032\026.google" +
      ".protobuf.Empty\"\000B\"\n\021com.scalar.dl.rpcB\013" +
      "ScalarProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.scalar.admin.rpc.AdminProto.getDescriptor(),
        });
    internal_static_rpc_CertificateRegistrationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_CertificateRegistrationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_CertificateRegistrationRequest_descriptor,
        new java.lang.String[] { "EntityId", "KeyVersion", "CertPem", });
    internal_static_rpc_SecretRegistrationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_SecretRegistrationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_SecretRegistrationRequest_descriptor,
        new java.lang.String[] { "EntityId", "KeyVersion", "SecretKey", });
    internal_static_rpc_FunctionRegistrationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rpc_FunctionRegistrationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_FunctionRegistrationRequest_descriptor,
        new java.lang.String[] { "FunctionId", "FunctionBinaryName", "FunctionByteCode", });
    internal_static_rpc_ContractRegistrationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rpc_ContractRegistrationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ContractRegistrationRequest_descriptor,
        new java.lang.String[] { "ContractId", "ContractBinaryName", "ContractByteCode", "ContractProperties", "EntityId", "KeyVersion", "Signature", });
    internal_static_rpc_ContractsListingRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_rpc_ContractsListingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ContractsListingRequest_descriptor,
        new java.lang.String[] { "EntityId", "KeyVersion", "ContractId", "Signature", });
    internal_static_rpc_ContractExecutionRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_rpc_ContractExecutionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ContractExecutionRequest_descriptor,
        new java.lang.String[] { "ContractId", "ContractArgument", "EntityId", "KeyVersion", "FunctionArgument", "Signature", "AuditorSignature", "UseFunctionIds", "FunctionIds", "Nonce", });
    internal_static_rpc_LedgerValidationRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_rpc_LedgerValidationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_LedgerValidationRequest_descriptor,
        new java.lang.String[] { "AssetId", "StartAge", "EndAge", "EntityId", "KeyVersion", "Signature", });
    internal_static_rpc_AssetProofRetrievalRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_rpc_AssetProofRetrievalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_AssetProofRetrievalRequest_descriptor,
        new java.lang.String[] { "AssetId", "Age", "EntityId", "KeyVersion", "Signature", });
    internal_static_rpc_ExecutionAbortRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_rpc_ExecutionAbortRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ExecutionAbortRequest_descriptor,
        new java.lang.String[] { "Nonce", "EntityId", "KeyVersion", "Signature", });
    internal_static_rpc_StateRetrievalRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_rpc_StateRetrievalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_StateRetrievalRequest_descriptor,
        new java.lang.String[] { "TransactionId", });
    internal_static_rpc_ExecutionValidationRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_rpc_ExecutionValidationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ExecutionValidationRequest_descriptor,
        new java.lang.String[] { "Request", "Proofs", });
    internal_static_rpc_ContractsListingResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_rpc_ContractsListingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ContractsListingResponse_descriptor,
        new java.lang.String[] { "Json", });
    internal_static_rpc_ContractExecutionResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_rpc_ContractExecutionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ContractExecutionResponse_descriptor,
        new java.lang.String[] { "ContractResult", "Proofs", "FunctionResult", });
    internal_static_rpc_LedgerValidationResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_rpc_LedgerValidationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_LedgerValidationResponse_descriptor,
        new java.lang.String[] { "StatusCode", "Proof", });
    internal_static_rpc_AssetProofRetrievalResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_rpc_AssetProofRetrievalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_AssetProofRetrievalResponse_descriptor,
        new java.lang.String[] { "Proof", "LedgerName", });
    internal_static_rpc_AssetProof_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_rpc_AssetProof_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_AssetProof_descriptor,
        new java.lang.String[] { "AssetId", "Age", "Nonce", "Input", "Hash", "PrevHash", "Signature", });
    internal_static_rpc_ExecutionAbortResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_rpc_ExecutionAbortResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ExecutionAbortResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_rpc_StateRetrievalResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_rpc_StateRetrievalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_StateRetrievalResponse_descriptor,
        new java.lang.String[] { "State", });
    internal_static_rpc_Status_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_rpc_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_Status_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_rpc_ExecutionOrderingResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_rpc_ExecutionOrderingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_ExecutionOrderingResponse_descriptor,
        new java.lang.String[] { "Signature", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.scalar.admin.rpc.AdminProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
