// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface SecretRegistrationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.SecretRegistrationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string entity_id = 1;</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 1;</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>uint32 key_version = 2;</code>
   * @return The keyVersion.
   */
  int getKeyVersion();

  /**
   * <code>string secret_key = 3;</code>
   * @return The secretKey.
   */
  java.lang.String getSecretKey();
  /**
   * <code>string secret_key = 3;</code>
   * @return The bytes for secretKey.
   */
  com.google.protobuf.ByteString
      getSecretKeyBytes();
}
