// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalar.proto

// Protobuf Java Version: 3.25.5
package com.scalar.dl.rpc;

public interface StateRetrievalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.StateRetrievalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transaction_id = 1;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 1;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();
}
