[[contracts]]
contract-id = "object.Put"
contract-binary-name = "com.scalar.dl.genericcontracts.object.Put"
contract-class-file = "generic-contracts/build/classes/java/main/com/scalar/dl/genericcontracts/object/Put.class"

[[contracts]]
contract-id = "object.Get"
contract-binary-name = "com.scalar.dl.genericcontracts.object.Get"
contract-class-file = "generic-contracts/build/classes/java/main/com/scalar/dl/genericcontracts/object/Get.class"

[[contracts]]
contract-id = "object.Validate"
contract-binary-name = "com.scalar.dl.genericcontracts.object.Validate"
contract-class-file = "generic-contracts/build/classes/java/main/com/scalar/dl/genericcontracts/object/Validate.class"

[[contracts]]
contract-id = "collection.Create"
contract-binary-name = "com.scalar.dl.genericcontracts.collection.Create"
contract-class-file = "generic-contracts/build/classes/java/main/com/scalar/dl/genericcontracts/collection/Create.class"

[[contracts]]
contract-id = "collection.Add"
contract-binary-name = "com.scalar.dl.genericcontracts.collection.Add"
contract-class-file = "generic-contracts/build/classes/java/main/com/scalar/dl/genericcontracts/collection/Add.class"

[[contracts]]
contract-id = "collection.Remove"
contract-binary-name = "com.scalar.dl.genericcontracts.collection.Remove"
contract-class-file = "generic-contracts/build/classes/java/main/com/scalar/dl/genericcontracts/collection/Remove.class"

[[contracts]]
contract-id = "collection.Get"
contract-binary-name = "com.scalar.dl.genericcontracts.collection.Get"
contract-class-file = "generic-contracts/build/classes/java/main/com/scalar/dl/genericcontracts/collection/Get.class"

[[contracts]]
contract-id = "collection.GetHistory"
contract-binary-name = "com.scalar.dl.genericcontracts.collection.GetHistory"
contract-class-file = "generic-contracts/build/classes/java/main/com/scalar/dl/genericcontracts/collection/GetHistory.class"

[[contracts]]
contract-id = "collection.GetCheckpointInterval"
contract-binary-name = "com.scalar.dl.genericcontracts.collection.GetCheckpointInterval"
contract-class-file = "generic-contracts/build/classes/java/main/com/scalar/dl/genericcontracts/collection/GetCheckpointInterval.class"
#contract-properties = '{"checkpoint_interval":10}'
