name: CI

on: 
  push:
    branches:
      - master
      - "[0-9]+"
      - "[0-9]+.[0-9]+"
  workflow_dispatch:
  pull_request:

jobs:
  check-generic-contracts-and-functions:
    name: Gradle check for generic contracts and functions
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: generic-contracts-and-functions

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check with Gradle
        run: ./gradlew check

      - name: Package artifacts
        if: always()
        run: |
          mkdir -p /tmp/artifacts-generic-contracts-and-functions
          cp -a build/reports/tests/test /tmp/artifacts-generic-contracts-and-functions/
          cp -a build/reports/spotbugs /tmp/artifacts-generic-contracts-and-functions/

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts-generic-contracts-and-functions
          path: /tmp/artifacts-generic-contracts-and-functions
